project:
  type: website
  output-dir: docs

website:
  title: "Quarto yml name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - Random.qmd

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true



